import Sidebar from "./components/Sidebar";
import "../../globals.css";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <aside className="h-screen">
            <Sidebar />
          </aside>
          <div className="w-full">
            <main className="p-2">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
